[build]
  ignore = "bash ./should-ignore-build.sh ${PROJECT_NAME}"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    path = ""
  
  [[plugins.inputs.audits]]
    path = "product/086_30521602"
  
  [[plugins.inputs.audits]]
    path = "category/4"

[functions.ssr]
  node_bundler = "esbuild"
  included_files = ["dist/apps/storefront/**"]
