export * from '../address-add-trigger/address-add-trigger.def';
export * from '../address-edit-trigger/address-edit-trigger.def';
export * from '../address-edit/address-edit.def';
export * from '../address-form/address-form.def';
export * from '../address-list-item/address-list-item.def';
export * from '../address-list/address-list.def';
export * from '../address-remove/address-remove.def';
export * from '../address/address.def';
export * from '../contact-form/contact-form.def';
