[[redirects]]
  from = "/"
  status = 200
  to = "/.netlify/functions/ssr"
  force = true
  [redirects.headers]
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' ; connect-src https: ; style-src 'self' 'unsafe-inline' https: ; form-action 'self'; script-src 'self' 'unsafe-inline' https: ; img-src https: data: ;  media-src https: base-uri 'self'; frame-src 'self' https://*.spryker.com https://*.netlify.com https://*.netlify.app https://*youtube.com;"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  status = 200
  to = "/.netlify/functions/ssr"
  [redirects.headers]
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' ; connect-src https: ; style-src 'self' 'unsafe-inline' https: ; form-action 'self'; script-src 'self' 'unsafe-inline' https: ; img-src https: data: ; media-src https: ; base-uri 'self'; frame-src 'self' https://*.spryker.com https://*.netlify.com https://*.netlify.app https://*youtube.com;"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
