export interface ProductImagesSet {
  /**
   * Image that is used to display preview
   */
  externalUrlLarge: string;

  /**
   * Image that is used to display thumbnail
   */
  externalUrlSmall: string;
}

export interface ProductImagesComponentOptions {
  /**
   * Preview layout
   * @default 'carousel'
   */
  previewLayout?: ProductImagesPreviewLayout;

  /**
   * Allows to position the navigation below or aside, or hide it.
   * @default 'below'
   */
  navigationPosition?: ProductImagesNavigationPosition;

  /**
   * Defines a layout type for the navigation
   * @default 'carousel'
   */
  navigationLayout?: ProductImagesNavigationLayout;

  /**
   * Allows to set floating state for navigation
   * @default 'inline'
   */
  navigationDisplay?: ProductImagesNavigationDisplay;

  /**
   * Allows to position navigation on the active axis
   */
  navigationAlignment?: ProductImagesNavigationAlignment;
}

export interface ProductImagesComponentSettings
  extends ProductImagesComponentOptions {
  /**
   * Preview image width
   * @default '300'
   */
  previewWidth?: number | string;

  /**
   * Preview image height
   * @default '300'
   */
  previewHeight?: number | string;

  /**
   * Thumb image width
   * @default '32'
   */
  thumbWidth?: number | string;

  /**
   * Thumb image height
   * @default '32'
   */
  thumbHeight?: number | string;

  /**
   * Unique name of the thumbs group
   * this parameter is needed for correct tab index of the navigation
   * it's generated by default based on component's uid
   * but can be set explicitly if needed
   * @default `product-image-nav-${this.uid}`
   */
  groupName?: string;
  hidePreview?: boolean;
  hideNavigation?: boolean;
}

export enum ProductImagesPreviewLayout {
  CAROUSEL = 'carousel',
  TOGGLE = 'toggle',
  NONE = 'none',
}

export enum ProductImagesNavigationPosition {
  START = 'start',
  END = 'end',
  BELOW = 'below',
}

export enum ProductImagesNavigationLayout {
  CAROUSEL = 'carousel',
  GRID = 'grid',
}

export enum ProductImagesNavigationDisplay {
  INLINE = 'inline',
  FLOATING = 'floating',
  NONE = 'none',
}

export enum ProductImagesNavigationAlignment {
  START = 'start',
  CENTER = 'center',
  END = 'end',
}

export enum ProductImagesScrollBehavior {
  Smooth = 'smooth',
  Auto = 'auto',
  Disable = 'disable',
}
