export enum StorefrontIconTypes {
  Dropdown = 'dropdown',
  DropUp = 'dropUp',
  Cart = 'cart',
  Expand = 'expand',
  Collapse = 'collapse',
  Add = 'cart-add',
  Increase = 'add',
  Decrease = 'minus',
  Search = 'search',
  Close = 'close',
  Image = 'image',
  InputError = 'inputError',
  Trash = 'trash',
  Info = 'info',
}
