[build]
  publish = "dist/client"
  command = "npm run build"

[[redirects]]
  from = "/"
  status = 200
  to = "/index.html"
  force = true
  [redirects.headers]
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' ; connect-src https: ; style-src 'self' 'unsafe-inline' https: ; form-action 'self'; script-src 'self' 'unsafe-inline' https: ; img-src https: data: ; media-src https: ; base-uri 'self'; frame-src 'self' https://*.spryker.com https://*.netlify.com https://*.netlify.app https://www.youtube.com ; object-src 'self' https://www.youtube.com"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"
  [redirects.headers]
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' ; connect-src https: ; style-src 'self' 'unsafe-inline' https: ; form-action 'self'; script-src 'self' 'unsafe-inline' https: ; img-src https: data: ; media-src https: ; base-uri 'self'; frame-src 'self' https://*.spryker.com https://*.netlify.com https://*.netlify.app https://www.youtube.com ; object-src 'self' https://www.youtube.com"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
