export interface ProductImage {
  /**
   * Image that is used to display preview
   */
  externalUrlLarge: string;
  /**
   * Image that is used to display thumbnail
   */
  externalUrlSmall: string;
}

export interface ProductImageComponentProperties {
  /**
   * Indicates the SKU of the product
   * used to request product data
   */
  code?: string;

  /**
   * Preview layout
   * @default 'carousel'
   */
  previewLayout?: ProductImagePreviewLayout;

  /**
   * Preview image width
   * @default '300'
   */
  previewWidth?: number | string;
  /**
   * Preview image height
   * @default '300'
   */
  previewHeight?: number | string;

  /**
   * Allows to position the thumbnail navigation below or aside, or hide it.
   * @default 'below'
   */
  thumbDisplay?: ProductImageNavigationDisplay;

  /**
   * Defines a layout type for the navigation
   * @default 'carousel'
   */
  thumbLayout?: ProductImageThumbsLayout;

  /**
   * Allows to set floating state for navigation
   * @default 'inline'
   */
  thumbPosition?: ProductImageThumbsPosition;

  /**
   * Unique name of the thumbs group
   * this parameter is needed for correct tab index of the navigation
   * it's randomly generated by default
   * but can be set explicitly if needed
   * @default `nav-${Math.round(Math.random() * 10000)}`
   */
  name?: string; // unique name of the thumbs group
  thumbWidth?: number | string; // thumb width
  thumbHeight?: number | string; // thumb height
}

export const enum ProductImagePreviewLayout {
  CAROUSEL = 'CAROUSEL',
  TOGGLE = 'toggle',
  NONE = 'none',
}

export const enum ProductImageNavigationDisplay {
  BELOW = 'below',
  ASIDE = 'aside',
  NONE = 'none',
}

export const enum ProductImageThumbsLayout {
  CAROUSEL = 'carousel',
  GRID = 'grid',
}

export const enum ProductImageThumbsPosition {
  CAROUSEL = 'inline',
  FLOATING = 'floating',
}
