export interface ProductImageSet {
  /**
   * Image that is used to display preview
   */
  externalUrlLarge: string;

  /**
   * Image that is used to display thumbnail
   */
  externalUrlSmall: string;
}

export interface ProductImageComponentOptions {
  /**
   * Preview layout
   * @default 'carousel'
   */
  previewLayout?: ProductImagePreviewLayout;

  /**
   * Allows to position the navigation below or aside, or hide it.
   * @default 'below'
   */
  navigationPosition?: ProductImageNavigationPosition;

  /**
   * Defines a layout type for the navigation
   * @default 'carousel'
   */
  navigationLayout?: ProductImageNavigationLayout;

  /**
   * Allows to set floating state for navigation
   * @default 'inline'
   */
  navigationDisplay?: ProductImageNavigationDisplay;

  /**
   * Allows to position navigation on the active axis
   */
  navigationAlignment?: ProductImageNavigationAlignment;
}

export interface ProductImageComponentSettings
  extends ProductImageComponentOptions {
  /**
   * Preview image width
   * @default '300'
   */
  previewWidth?: number | string;

  /**
   * Preview image height
   * @default '300'
   */
  previewHeight?: number | string;

  /**
   * Thumb image width
   * @default '32'
   */
  thumbWidth?: number | string;

  /**
   * Thumb image height
   * @default '32'
   */
  thumbHeight?: number | string;

  /**
   * Unique name of the thumbs group
   * this parameter is needed for correct tab index of the navigation
   * it's generated by default based on component's uid
   * but can be set explicitly if needed
   * @default `product-image-nav-${this.uid}`
   */
  groupName?: string;
  showPreview?: boolean;
  showNavigation?: boolean;
}

export enum ProductImagePreviewLayout {
  CAROUSEL = 'carousel',
  TOGGLE = 'toggle',
  NONE = 'none',
}

export enum ProductImageNavigationPosition {
  START = 'start',
  END = 'end',
  BELOW = 'below',
}

export enum ProductImageNavigationLayout {
  CAROUSEL = 'carousel',
  GRID = 'grid',
}

export enum ProductImageNavigationDisplay {
  INLINE = 'inline',
  FLOATING = 'floating',
  NONE = 'none',
}

export enum ProductImageNavigationAlignment {
  START = 'start',
  CENTER = 'center',
  END = 'end',
}

export enum ProductImageScrollBehavior {
  SMOOTH = 'smooth',
  AUTO = 'auto',
}
