export interface ProductImageSet {
  /**
   * Image that is used to display preview
   */
  externalUrlLarge: string;

  /**
   * Image that is used to display thumbnail
   */
  externalUrlSmall: string;
}

export interface ProductImageComponentProperties {
  /**
   * Indicates the SKU of the product
   * used to request product data
   */
  code?: string;

  /**
   * Preview layout
   * @default 'carousel'
   */
  previewLayout?: ProductImagePreviewLayout;

  /**
   * Allows to position the navigation below or aside, or hide it.
   * @default 'below'
   */
  navigationDisplay?: ProductImageNavigationDisplay;

  /**
   * Defines a layout type for the navigation
   * @default 'carousel'
   */
  navigationLayout?: ProductImageNavigationLayout;

  /**
   * Allows to set floating state for navigation
   * @default 'inline'
   */
  navigationPosition?: ProductImageNavigationPosition;
}

export interface ProductImageComponentSettings
  extends ProductImageComponentProperties {
  /**
   * Preview image width
   * @default '300'
   */
  previewWidth?: number | string;

  /**
   * Preview image height
   * @default '300'
   */
  previewHeight?: number | string;

  /**
   * Thumb image width
   * @default '32'
   */
  thumbWidth?: number | string;

  /**
   * Thumb image height
   * @default '32'
   */
  thumbHeight?: number | string;

  /**
   * Unique name of the thumbs group
   * this parameter is needed for correct tab index of the navigation
   * it's randomly generated by default
   * but can be set explicitly if needed
   * @default `product-image-nav-${this.uid}`
   */
  groupName?: string;
  showPreview?: boolean;
  showNavigation?: boolean;
}

export enum ProductImagePreviewLayout {
  CAROUSEL = 'carousel',
  TOGGLE = 'toggle',
  NONE = 'none',
}

export enum ProductImageNavigationDisplay {
  BELOW = 'below',
  ASIDE = 'aside',
  NONE = 'none',
}

export enum ProductImageNavigationLayout {
  CAROUSEL = 'carousel',
  GRID = 'grid',
}

export enum ProductImageNavigationPosition {
  INLINE = 'inline',
  FLOATING = 'floating',
}
