export * from '../banner/banner.def';
export * from '../contact/contact.def';
export * from '../description/description.def';
export * from '../legal/legal.def';
export * from '../logo/logo.def';
export * from '../offer-list-item/offer-list-item.def';
export * from '../offer-list/offer-list.def';
export * from '../opening-hours/opening-hours.def';
export * from '../title/title.def';
