import { IconMapper } from '@spryker-oryx/experience';
import { IconTypes } from '../icon.model';

export const backofficeFontAwesomeIcons: IconMapper = {
  id: 'fa',
  styles: `
    --oryx-icon-font: 'Font Awesome 6 Free';
    --oryx-icon-weight: 900;
  `,
  mapping: {
    [IconTypes.CartAdd]: '&#xf217;',
    [IconTypes.Cart]: '&#xf07a;',
    [IconTypes.Close]: '&#xf00d;',
    [IconTypes.Add]: '&#x2b;',
    [IconTypes.Increase]: '&#x2b;', // merge with add
    [IconTypes.Collapse]: '&#x2b;', // merge with add
    [IconTypes.DropUp]: '&#xf106;',
    [IconTypes.Dropdown]: '&#xf107;',
    [IconTypes.Minus]: '&#xf068;',
    [IconTypes.Decrease]: '&#xf068;', // merge with minus
    [IconTypes.Expand]: '&#xf068;', // merge with minus
    [IconTypes.Image]: '&#xf03e;',
    [IconTypes.Mark]: '&#xf00c;',
    [IconTypes.Remove]: '&#xf057;',
    [IconTypes.Rocket]: '&#xf135;',
    [IconTypes.Search]: '&#xf002;',
    [IconTypes.Trash]: '&#xf2ed;',
    [IconTypes.Visible]: '&#xf06e;',
    [IconTypes.Invisible]: '&#xf070;',
    [IconTypes.Wishlist]: '&#xf004;',
    [IconTypes.User]: '&#xf007;',
    [IconTypes.Customer]: '&#xf007;', // merge with user
    [IconTypes.Ratings]: '&#xe561;',
    [IconTypes.Sales]: '&#xf555;',
    [IconTypes.Users]: '&#xf0c0;',
    [IconTypes.ModeDark]: '&#xf186;',
    [IconTypes.ModeLight]: '&#xf185;',
    [IconTypes.Orders]: '&#xf218;',
    [IconTypes.Products]: '&#xf466;',
    [IconTypes.Profile]: '&#xf508;',
    [IconTypes.Desktop]: '&#xf390;',
    [IconTypes.Mobile]: '&#xf3cd;',
    [IconTypes.Tablet]: '&#xf3fa;',
    [IconTypes.Info]: '&#xf05a;',
    [IconTypes.Error]: '&#xf05e;',
    [IconTypes.InputError]: '&#xf05e;', // merge with error
    [IconTypes.Success]: '&#xf058;',
    [IconTypes.Warning]: '&#xf06a;',
    [IconTypes.Planet]: '&#xf0ac;',
    [IconTypes.Actions]: '&#xf142;',
    [IconTypes.ActionsHorizontal]: '&#xf141;',
    [IconTypes.Back]: '&#xf104;',
    [IconTypes.Bottom]: '&#xe4b8;',
    [IconTypes.Calendar]: '&#xf073;',
    [IconTypes.Copy]: '&#xf0c5;',
    [IconTypes.Create]: '&#xf0fe;',
    [IconTypes.Disconnect]: '&#xe55e;',
    [IconTypes.Drag]: '&#xf850;',
    [IconTypes.DragSmall]: '&#xf58e;',
    [IconTypes.Edit]: '&#xf304;',
    [IconTypes.File]: '&#xf15b;',
    [IconTypes.Filter]: '&#xf0dc;',
    [IconTypes.Filters]: '&#xf085;',
    [IconTypes.Front]: '&#xf105;',
    [IconTypes.Help]: '&#xf059;',
    [IconTypes.Imports]: '&#xf019;',
    [IconTypes.InputStepper]: '&#xf0d8;',
    [IconTypes.Link]: '&#xf08e;',
    [IconTypes.Loader]: '&#xf110;',
    [IconTypes.Locker]: '&#xf023;',
    [IconTypes.Maximize]: '&#xf424;',
    [IconTypes.Menu]: '&#xf0c9;',
    [IconTypes.Minimize]: '&#xf422;',
    [IconTypes.NavigationArrow]: '&#xf061;',
    [IconTypes.Reset]: '&#xf2f9;',
    [IconTypes.Settings]: '&#xf013;',
    [IconTypes.Sort]: '&#xf0dc;',
    [IconTypes.Star]: '&#xf005;',
    [IconTypes.Top]: '&#xe4c2;',
    [IconTypes.List]: '&#xf03a;',
    [IconTypes.ArrowsOutward]: '&#xf337;',
    [IconTypes.ViewList]: '&#xf00b;',
    [IconTypes.Composition]: '&#xf00a;',
    [IconTypes.BulletList]: '&#xf0ca;',
    [IconTypes.Login]: '&#xf090;',
    [IconTypes.Video]: '&#xf03d;',
    [IconTypes.Description]: '&#xf46d;',
    [IconTypes.Barcode]: '&#xf02a;',
    [IconTypes.Images]: '&#xf302;',
    [IconTypes.Label]: '&#xf02b;',
    [IconTypes.Media]: '&#xf87c;',
    [IconTypes.Price]: '&#xf0d6;',
    [IconTypes.Title]: '&#xf1dc;',
    [IconTypes.Card]: '&#xf249;',
    [IconTypes.Input]: '&#xf2f6;',
  },
};

export const backofficeFontIcons = {
  [backofficeFontAwesomeIcons.id]:
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css',
};
